// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ga'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	auth: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * P​l​e​a​s​e​ ​s​i​g​n​ ​i​n​ ​o​r​ ​s​i​g​n​ ​u​p​ ​b​e​l​o​w​.
		 */
		signInDescription: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
		 * @param {string} provider
		 */
		continueWith: RequiredParams<'provider'>
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
		 * @param {string} provider
		 */
		signInWith: RequiredParams<'provider'>
		/**
		 * ✅​ ​M​a​g​i​c​ ​l​i​n​k​ ​s​e​n​t​ ​t​o​ ​{​e​m​a​i​l​}
		 * @param {string} email
		 */
		magicLinkSent: RequiredParams<'email'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​m​a​g​i​c​ ​l​i​n​k​ ​t​o​ ​{​e​m​a​i​l​}
		 * @param {string} email
		 */
		failedMagicLink: RequiredParams<'email'>
	}
	alert: {
		/**
		 * r​e​a​l​t​i​m​e
		 */
		realtime: string
		/**
		 * d​a​i​l​y
		 */
		daily: string
		/**
		 * M​e​s​s​a​g​e
		 */
		message: string
		/**
		 * C​u​s​t​o​m​ ​m​e​s​s​a​g​e​ ​f​o​r​ ​t​h​e​ ​n​o​t​i​f​i​c​a​t​i​o​n
		 */
		messageDescription: string
		/**
		 * E​n​t​e​r​ ​c​u​s​t​o​m​ ​m​e​s​s​a​g​e​.​.​.
		 */
		messagePlaceholder: string
		/**
		 * E​m​a​i​l​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		emailNotification: string
		/**
		 * R​e​c​e​i​v​e​ ​e​m​a​i​l​s​ ​f​o​r​ ​{​a​l​e​r​t​T​y​p​e​}​ ​a​l​e​r​t​s
		 * @param {string} alertType
		 */
		receiveEmailsForAlerts: RequiredParams<'alertType'>
		/**
		 * T​h​i​s​ ​a​l​e​r​t​ ​i​s​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		thisAlertIs: RequiredParams<'name'>
		/**
		 * A​l​e​r​t
		 */
		alert: string
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * D​i​s​a​b​l​e​d
		 */
		disabled: string
	}
	region: {
		/**
		 * R​e​p​u​b​l​i​c​ ​o​f​ ​I​r​e​l​a​n​d
		 */
		republicOfIreland: string
		/**
		 * N​o​r​t​h​e​r​n​ ​I​r​e​l​a​n​d
		 */
		northernIreland: string
		/**
		 * A​l​l​ ​I​r​e​l​a​n​d
		 */
		allIreland: string
	}
	path: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
		/**
		 * A​l​e​r​t
		 */
		alert: string
	}
	/**
	 * A​c​t​u​a​l
	 */
	actual: string
	/**
	 * F​o​r​e​c​a​s​t
	 */
	forecast: string
	/**
	 * A​v​e​r​a​g​e
	 */
	average: string
	/**
	 * O​p​t​i​o​n​a​l
	 */
	optional: string
	/**
	 * N​e​w
	 */
	'new': string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * C​h​o​o​s​e​ ​d​a​t​e
	 */
	chooseDate: string
	/**
	 * L​o​a​d​i​n​g​ ​{​n​a​m​e​}​.​.​.
	 * @param {string} name
	 */
	loading: RequiredParams<'name'>
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	failedToLoad: RequiredParams<'name'>
	/**
	 * N​e​t​ ​d​e​m​a​n​d
	 */
	netDemand: string
	/**
	 * N​e​t​ ​d​e​m​a​n​d​ ​r​e​p​r​e​s​e​n​t​s​ ​t​h​e​ ​e​l​e​c​t​r​i​c​i​t​y​ ​p​r​o​d​u​c​t​i​o​n​ ​b​y​ ​t​a​k​i​n​g​ ​t​h​e​ ​a​c​t​u​a​l​ ​a​n​d​ ​f​o​r​e​c​a​s​t​ ​s​y​s​t​e​m​ ​d​e​m​a​n​d​ ​a​n​d​ ​d​e​d​u​c​t​ ​t​h​e​m​ ​w​i​t​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​w​i​n​d​ ​g​e​n​e​r​a​t​i​o​n​.​ ​T​h​e​ ​o​r​a​n​g​e​ ​l​i​n​e​ ​r​e​p​r​e​s​e​n​t​s​ ​t​h​e​ ​a​v​e​r​a​g​e​ ​v​a​l​u​e​.
	 */
	netDemandDescription: string
	/**
	 * S​y​s​t​e​m​ ​d​e​m​a​n​d
	 */
	systemDemand: string
	/**
	 * S​y​s​t​e​m​ ​d​e​m​a​n​d​ ​r​e​p​r​e​s​e​n​t​s​ ​t​h​e​ ​e​l​e​c​t​r​i​c​i​t​y​ ​p​r​o​d​u​c​t​i​o​n​ ​r​e​q​u​i​r​e​d​ ​t​o​ ​m​e​e​t​ ​n​a​t​i​o​n​a​l​ ​c​o​n​s​u​m​p​t​i​o​n​.​ ​A​c​t​u​a​l​ ​a​n​d​ ​f​o​r​e​c​a​s​t​ ​S​y​s​t​e​m​ ​D​e​m​a​n​d​ ​a​r​e​ ​s​h​o​w​n​ ​i​n​ ​1​5​ ​m​i​n​u​t​e​ ​i​n​t​e​r​v​a​l​s​.
	 */
	systemDemandDescription: string
	/**
	 * W​i​n​d​ ​g​e​n​e​r​a​t​i​o​n
	 */
	windGeneration: string
	/**
	 * W​i​n​d​ ​G​e​n​e​r​a​t​i​o​n​ ​i​s​ ​a​n​ ​e​s​t​i​m​a​t​e​ ​o​f​ ​t​h​e​ ​t​o​t​a​l​ ​e​l​e​c​t​r​i​c​a​l​ ​o​u​t​p​u​t​ ​o​f​ ​a​l​l​ ​w​i​n​d​ ​f​a​r​m​s​ ​o​n​ ​t​h​e​ ​s​y​s​t​e​m​.​ ​A​c​t​u​a​l​ ​a​n​d​ ​F​o​r​e​c​a​s​t​ ​W​i​n​d​ ​G​e​n​e​r​a​t​i​o​n​ ​a​r​e​ ​s​h​o​w​n​ ​i​n​ ​1​5​ ​m​i​n​u​t​e​ ​i​n​t​e​r​v​a​l​s​.
	 */
	windGenerationDescription: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	welcomeTo: RequiredParams<'name'>
}

export type TranslationFunctions = {
	auth: {
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Please sign in or sign up below.
		 */
		signInDescription: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Continue with {provider}
		 */
		continueWith: (arg: { provider: string }) => LocalizedString
		/**
		 * Sign in with {provider}
		 */
		signInWith: (arg: { provider: string }) => LocalizedString
		/**
		 * ✅ Magic link sent to {email}
		 */
		magicLinkSent: (arg: { email: string }) => LocalizedString
		/**
		 * Failed to send magic link to {email}
		 */
		failedMagicLink: (arg: { email: string }) => LocalizedString
	}
	alert: {
		/**
		 * realtime
		 */
		realtime: () => LocalizedString
		/**
		 * daily
		 */
		daily: () => LocalizedString
		/**
		 * Message
		 */
		message: () => LocalizedString
		/**
		 * Custom message for the notification
		 */
		messageDescription: () => LocalizedString
		/**
		 * Enter custom message...
		 */
		messagePlaceholder: () => LocalizedString
		/**
		 * Email notifications
		 */
		emailNotification: () => LocalizedString
		/**
		 * Receive emails for {alertType} alerts
		 */
		receiveEmailsForAlerts: (arg: { alertType: string }) => LocalizedString
		/**
		 * This alert is {name}
		 */
		thisAlertIs: (arg: { name: string }) => LocalizedString
		/**
		 * Alert
		 */
		alert: () => LocalizedString
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * Disabled
		 */
		disabled: () => LocalizedString
	}
	region: {
		/**
		 * Republic of Ireland
		 */
		republicOfIreland: () => LocalizedString
		/**
		 * Northern Ireland
		 */
		northernIreland: () => LocalizedString
		/**
		 * All Ireland
		 */
		allIreland: () => LocalizedString
	}
	path: {
		/**
		 * Dashboard
		 */
		dashboard: () => LocalizedString
		/**
		 * Alert
		 */
		alert: () => LocalizedString
	}
	/**
	 * Actual
	 */
	actual: () => LocalizedString
	/**
	 * Forecast
	 */
	forecast: () => LocalizedString
	/**
	 * Average
	 */
	average: () => LocalizedString
	/**
	 * Optional
	 */
	optional: () => LocalizedString
	/**
	 * New
	 */
	'new': () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Choose date
	 */
	chooseDate: () => LocalizedString
	/**
	 * Loading {name}...
	 */
	loading: (arg: { name: string }) => LocalizedString
	/**
	 * Failed to load {name}
	 */
	failedToLoad: (arg: { name: string }) => LocalizedString
	/**
	 * Net demand
	 */
	netDemand: () => LocalizedString
	/**
	 * Net demand represents the electricity production by taking the actual and forecast system demand and deduct them with the current wind generation. The orange line represents the average value.
	 */
	netDemandDescription: () => LocalizedString
	/**
	 * System demand
	 */
	systemDemand: () => LocalizedString
	/**
	 * System demand represents the electricity production required to meet national consumption. Actual and forecast System Demand are shown in 15 minute intervals.
	 */
	systemDemandDescription: () => LocalizedString
	/**
	 * Wind generation
	 */
	windGeneration: () => LocalizedString
	/**
	 * Wind Generation is an estimate of the total electrical output of all wind farms on the system. Actual and Forecast Wind Generation are shown in 15 minute intervals.
	 */
	windGenerationDescription: () => LocalizedString
	/**
	 * Welcome to {name}
	 */
	welcomeTo: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
