// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ga'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	auth: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * P​l​e​a​s​e​ ​s​i​g​n​ ​i​n​ ​o​r​ ​s​i​g​n​ ​u​p​ ​b​e​l​o​w​.
		 */
		signInDescription: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
		 * @param {string} provider
		 */
		continueWith: RequiredParams<'provider'>
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
		 * @param {string} provider
		 */
		signInWith: RequiredParams<'provider'>
		/**
		 * ✅​ ​M​a​g​i​c​ ​l​i​n​k​ ​s​e​n​t​ ​t​o​ ​{​e​m​a​i​l​}
		 * @param {string} email
		 */
		magicLinkSent: RequiredParams<'email'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​m​a​g​i​c​ ​l​i​n​k​ ​t​o​ ​{​e​m​a​i​l​}
		 * @param {string} email
		 */
		failedMagicLink: RequiredParams<'email'>
	}
	alert: {
		newAlertForm: {
			/**
			 * B​y​ ​c​r​e​a​t​i​n​g​ ​a​ ​n​e​w​ ​a​l​e​r​t​,​ ​y​o​u​ ​w​i​l​l​ ​r​e​c​e​i​v​e​ ​n​o​t​i​f​i​c​a​t​i​o​n​ ​o​n​c​e​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​c​o​n​d​i​t​i​o​n​ ​w​a​s​ ​t​r​i​g​g​e​r​e​d​.
			 */
			subtitle: string
			name: {
				/**
				 * N​a​m​e
				 */
				label: string
				/**
				 * N​a​m​e​ ​o​f​ ​t​h​e​ ​a​l​e​r​t
				 */
				description: string
			}
			description: {
				/**
				 * D​e​s​c​r​i​p​t​i​o​n
				 */
				label: string
				/**
				 * D​e​s​c​r​i​p​t​i​o​n​ ​o​f​ ​t​h​e​ ​a​l​e​r​t
				 */
				description: string
			}
			threshold: {
				/**
				 * T​h​r​e​s​h​o​l​d
				 */
				label: string
				/**
				 * D​e​s​i​r​e​d​ ​t​h​r​e​s​h​o​l​d​ ​(​u​s​e​ ​i​n​ ​c​o​m​b​i​n​a​t​i​o​n​ ​w​i​t​h​ ​c​o​m​p​a​r​a​t​o​r​)
				 */
				description: string
			}
			comparator: {
				/**
				 * C​o​m​p​a​r​a​t​o​r
				 */
				label: string
				/**
				 * T​o​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​t​h​r​e​s​h​o​l​d​ ​w​i​t​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​v​a​l​u​e
				 */
				description: string
			}
			alertType: {
				/**
				 * A​l​e​r​t​ ​t​y​p​e
				 */
				label: string
				/**
				 * T​y​p​e​ ​o​f​ ​a​l​e​r​t
				 */
				description: string
			}
			message: {
				/**
				 * M​e​s​s​a​g​e
				 */
				label: string
				/**
				 * M​e​s​s​a​g​e​ ​t​o​ ​b​e​ ​s​e​n​t​ ​w​h​e​n​ ​t​h​e​ ​a​l​e​r​t​ ​i​s​ ​t​r​i​g​g​e​r​e​d
				 */
				description: string
			}
		}
		/**
		 * T​h​i​s​ ​a​l​e​r​t​ ​i​s​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		thisAlertIs: RequiredParams<'name'>
		/**
		 * A​l​e​r​t
		 */
		alert: string
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * D​i​s​a​b​l​e​d
		 */
		disabled: string
	}
	/**
	 * O​p​t​i​o​n​a​l
	 */
	optional: string
	/**
	 * N​e​w
	 */
	'new': string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * L​o​a​d​i​n​g​ ​{​n​a​m​e​}​.​.​.
	 * @param {string} name
	 */
	loading: RequiredParams<'name'>
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	failedToLoad: RequiredParams<'name'>
	/**
	 * S​y​s​t​e​m​ ​d​e​m​a​n​d
	 */
	systemDemand: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	welcomeTo: RequiredParams<'name'>
}

export type TranslationFunctions = {
	auth: {
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Please sign in or sign up below.
		 */
		signInDescription: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Continue with {provider}
		 */
		continueWith: (arg: { provider: string }) => LocalizedString
		/**
		 * Sign in with {provider}
		 */
		signInWith: (arg: { provider: string }) => LocalizedString
		/**
		 * ✅ Magic link sent to {email}
		 */
		magicLinkSent: (arg: { email: string }) => LocalizedString
		/**
		 * Failed to send magic link to {email}
		 */
		failedMagicLink: (arg: { email: string }) => LocalizedString
	}
	alert: {
		newAlertForm: {
			/**
			 * By creating a new alert, you will receive notification once the specified condition was triggered.
			 */
			subtitle: () => LocalizedString
			name: {
				/**
				 * Name
				 */
				label: () => LocalizedString
				/**
				 * Name of the alert
				 */
				description: () => LocalizedString
			}
			description: {
				/**
				 * Description
				 */
				label: () => LocalizedString
				/**
				 * Description of the alert
				 */
				description: () => LocalizedString
			}
			threshold: {
				/**
				 * Threshold
				 */
				label: () => LocalizedString
				/**
				 * Desired threshold (use in combination with comparator)
				 */
				description: () => LocalizedString
			}
			comparator: {
				/**
				 * Comparator
				 */
				label: () => LocalizedString
				/**
				 * To compare the threshold with the current value
				 */
				description: () => LocalizedString
			}
			alertType: {
				/**
				 * Alert type
				 */
				label: () => LocalizedString
				/**
				 * Type of alert
				 */
				description: () => LocalizedString
			}
			message: {
				/**
				 * Message
				 */
				label: () => LocalizedString
				/**
				 * Message to be sent when the alert is triggered
				 */
				description: () => LocalizedString
			}
		}
		/**
		 * This alert is {name}
		 */
		thisAlertIs: (arg: { name: string }) => LocalizedString
		/**
		 * Alert
		 */
		alert: () => LocalizedString
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * Disabled
		 */
		disabled: () => LocalizedString
	}
	/**
	 * Optional
	 */
	optional: () => LocalizedString
	/**
	 * New
	 */
	'new': () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Loading {name}...
	 */
	loading: (arg: { name: string }) => LocalizedString
	/**
	 * Failed to load {name}
	 */
	failedToLoad: (arg: { name: string }) => LocalizedString
	/**
	 * System demand
	 */
	systemDemand: () => LocalizedString
	/**
	 * Welcome to {name}
	 */
	welcomeTo: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
